// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtEj2Zlc1yOE_lNZTXtwL_5X-6FMms79w',
    appId: '1:532378505949:web:335e23f11c396a235f4134',
    messagingSenderId: '532378505949',
    projectId: 'my-social-app-9e8f8',
    authDomain: 'my-social-app-9e8f8.firebaseapp.com',
    storageBucket: 'my-social-app-9e8f8.appspot.com',
    measurementId: 'G-BF36V0MXMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgqEMRoqItXciFJyp8F6KyJyLrynDpnfM',
    appId: '1:532378505949:android:47603e9fb5392c905f4134',
    messagingSenderId: '532378505949',
    projectId: 'my-social-app-9e8f8',
    storageBucket: 'my-social-app-9e8f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz6iYbVC8NxiucOKtS9q2aWhCxrWlQPfo',
    appId: '1:532378505949:ios:92d0b1064554b8445f4134',
    messagingSenderId: '532378505949',
    projectId: 'my-social-app-9e8f8',
    storageBucket: 'my-social-app-9e8f8.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz6iYbVC8NxiucOKtS9q2aWhCxrWlQPfo',
    appId: '1:532378505949:ios:22ce2ecf89a3643f5f4134',
    messagingSenderId: '532378505949',
    projectId: 'my-social-app-9e8f8',
    storageBucket: 'my-social-app-9e8f8.appspot.com',
    iosBundleId: 'com.example.socialMedia.RunnerTests',
  );
}
